import TopNavbar from '@/layout/main/TopNavbar';
export const metadata = {
  title: 'Fruitzy | Home',
  description: 'Generated by fruitzy app'
};

export default function RootLayout({ children }) {
  return <TopNavbar>{children}</TopNavbar>;
}
